version: '3'
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      - "MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}"
      - "MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}"
      - "MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}"
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./.mongo/data:/data/db
      - ./.mongo/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./.mongo/configdb:/data/configdb
    command: mongod --smallfiles

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

    
